In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import pylab as pl
from sklearn import preprocessing
import scipy.optimize as opt
from sklearn.preprocessing import LabelEncoder


In [2]:
data=pd.read_csv((r'C:\Users\Ghalamkarian\PycharmProjects\pythonProject3\data_breastcancer.csv'))

In [4]:
data.tail()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
564                0.2216          0.2060                  0.07115  
565                0.1628          0.2572                  0.06637  
566                0.1418          0.2218                  0.07820  
567                0.2650          0.4087                  0.12400  
568                0.0000          0.2871                  0.07039  

[5 rows x 32 columns]

In [4]:
data.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [5]:
ya=data['diagnosis']
le=LabelEncoder()
encoderdata4=le.fit_transform(ya)
data['diagnosis']=encoderdata4

In [6]:
data.tail()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424          1        21.56         22.39          142.00     1479.0   
565  926682          1        20.13         28.25          131.20     1261.0   
566  926954          1        16.60         28.08          108.30      858.1   
567  927241          1        20.60         29.33          140.10     1265.0   
568   92751          0         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
564                0.2216          0.2060                  0.07115  
565                0.1628          0.2572                  0.06637  
566                0.1418          0.2218                  0.07820  
567                0.2650          0.4087                  0.12400  
568                0.0000          0.2871                  0.07039  

[5 rows x 32 columns]

In [7]:
X=data[['radius_mean','texture_mean','perimeter_mean','smoothness_mean','compactness_mean']]#.values
x=np.asarray(X)
x[0:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.184e-01, 2.776e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 8.474e-02, 7.864e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.096e-01, 1.599e-01],
       [1.142e+01, 2.038e+01, 7.758e+01, 1.425e-01, 2.839e-01],
       [2.029e+01, 1.434e+01, 1.351e+02, 1.003e-01, 1.328e-01]])

In [8]:
Y=data['diagnosis']
y=np.asarray(Y)
y[0:5]
Y.value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [9]:
#normalize
scalearn=preprocessing.StandardScaler()
x=scalearn.fit(x).transform(x)
x[0:5]


array([[ 1.09706398, -2.07333501,  1.26993369,  1.56846633,  3.28351467],
       [ 1.82982061, -0.35363241,  1.68595471, -0.82696245, -0.48707167],
       [ 1.57988811,  0.45618695,  1.56650313,  0.94221044,  1.05292554],
       [-0.76890929,  0.25373211, -0.59268717,  3.28355348,  3.40290899],
       [ 1.75029663, -1.15181643,  1.77657315,  0.28037183,  0.53934045]])

In [10]:
#train & test 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
x_test
x_train

array([[-0.8711544 , -1.00753827, -0.84353549,  0.49386816, -0.25339993],
       [ 0.23366083, -0.40017375,  0.20104799,  1.44748508,  0.49575205],
       [ 0.20809955, -0.54677898,  0.1203152 , -0.50671796, -0.63678836],
       ...,
       [-0.03047238, -0.84464357, -0.09799286, -1.18848289, -0.91973395],
       [-0.98476008, -0.963324  , -1.00829629, -0.60065634, -1.16212337],
       [ 2.87499285,  0.2118449 ,  3.05758838,  3.44011745,  3.45597313]])

In [11]:
data.size


18208

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
lr=LogisticRegression(C=0.01).fit(x_train,y_train)
lr

LogisticRegression(C=0.01)

In [13]:
yhat=lr.predict(x_test)
yhat.reshape
print(yhat[0:10])
print(y_test[0:10])

[0 0 1 1 0 0 0 0 0 0]
[0 0 1 1 0 0 0 0 1 0]


In [14]:
yhat_proba=lr.predict_proba(x_test)
yhat_proba[0:10]

array([[0.63381426, 0.36618574],
       [0.77791704, 0.22208296],
       [0.14503858, 0.85496142],
       [0.33095092, 0.66904908],
       [0.51584244, 0.48415756],
       [0.58406002, 0.41593998],
       [0.90608244, 0.09391756],
       [0.80115905, 0.19884095],
       [0.57239455, 0.42760545],
       [0.84356358, 0.15643642]])

In [15]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat, pos_label=1)


0.8378378378378378

In [16]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat, pos_label=0)

0.927710843373494

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        80
           1       0.91      0.91      0.91        34

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

